title: ELECTRO PERFORMANCE SRL 
author: Valentin Pomirleanu 
email: valentin.pomirleanu @ gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Lorem Ipsum

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
